### ISSUE TITLE
when i run  `make verify`,there is an error:

### ISSUE THREAD

**Issue by philtruing** [contract-ace/smartace#3]
I've installed smartACE from the source code,when i run  `make verify`,there is an error:
make verify
make: *** No rule to make target 'verify'.  Stop.
Should I install seahorn and Klee separately?

**Comment by ScottWe** [comment]
Hi @philtruing.

If you wish to use model checking in SmartACE then you must install `seahorn`.

If seahorn is already installed on your machine, then SmartACE is unable to find `sea`. You can fix this by running `cmake -DSEA_PATH=/path/to/sea/exectuable .` instead of `cmake .`.

I hope this helps!

edit: typo in commands

**Comment by jcrreis** [comment]
Hello @ScottWe,

If I understood correctly, to use model checking with seahorn we need to specify properties with Scribble before right?

Thank you.

**Comment by ScottWe** [comment]
Hi @jcrreis,

SmartACE doesn't have its own specification language. If your smart contract has assertions, then SmartACE will check if any of the assertions can be violated. This is what we did in SAS2021.

In VMCAI2022 we also looked at Scribble as a specification language. If you'd like to use Scribble, then you can find some examples in https://github.com/contract-ace/verify-openzeppelin.

Hope that helps.

- Scott
