### ISSUE TITLE
Error running with 0.8.11 solidity contract

### ISSUE THREAD

**Issue by jcrreis** [contract-ace/smartace#4]
Hello,

I installed SmartAce from this repository source code, but when i try to run:

```
./build/run/bin/solc contract.sol --c-model --output-dir=example
```

I get:
```
Error: Source file requires different compiler version (current compiler is 0.5.9-develop.2022.6.4+commit.b6a012ea.mod.Linux.g++ - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.8.11;
```

Does this project work for recent 0.8+ solidity versions? Or this only supports 0.5.9? If it supports 0.8+ version how can I fix this? I have solc 0.8.11, 0.8.13 and 0.8.7 installed with solc-select.

Thank you.

**Comment by ScottWe** [comment]
Hi João,

Unfortunately SmartACE is fixed at 0.5.9. The internal representation used by solc has changed between 0.5.9 and 0.8, so SmartACE would need to be updated accordingly.

_Note that SmartACE only uses the Solidity compiler for parsing and code analysis, so backporting you code might work if the features in your contract have not changed significantly since 0.5.9._
